name: menu-cms
on:
 issues:
   types: [opened]
jobs:
 update:
   runs-on: ubuntu-latest
   permissions:
     contents: write
     issues: read
   steps:
     - uses: actions/checkout@v4
     - name: parse issue
       run: |
         echo "${{ github.event.issue.title }}" > title.txt
         echo "${{ github.event.issue.body }}" > body.txt
     - name: commit
       run: |
         git config user.name "cms-bot"
         git config user.email "bot@github"
         git add .
         git commit -m "CMS update"
         git push